<?php

namespace Webkul\Installer\Database\Seeders\Attribute;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @param  array  $parameters
     * @return void
     */
    public function run($parameters = [])
    {
        DB::table('attributes')->delete();

        $now = Carbon::now();

        $defaultLocale = $parameters['locale'] ?? config('app.locale');

        DB::table('attributes')->insert([
            /**
             * Leads Attributes
             */
            [
                'code' => 'title',
                'name' => trans('installer::app.seeders.attributes.leads.title', [], $defaultLocale),
                'type' => 'text',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '1',
                'is_required' => '1',
                'is_unique' => '0',
                'quick_add' => '1',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'description',
                'name' => trans('installer::app.seeders.attributes.leads.description', [], $defaultLocale),
                'type' => 'textarea',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '2',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '1',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'lead_value',
                'name' => trans('installer::app.seeders.attributes.leads.lead-value', [], $defaultLocale),
                'type' => 'price',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => 'decimal',
                'sort_order' => '3',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'lead_source_id',
                'name' => trans('installer::app.seeders.attributes.leads.source', [], $defaultLocale),
                'type' => 'select',
                'entity_type' => 'leads',
                'lookup_type' => 'lead_sources',
                'validation' => null,
                'sort_order' => '4',
                'is_required' => '1',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'lead_type_id',
                'name' => trans('installer::app.seeders.attributes.leads.type', [], $defaultLocale),
                'type' => 'select',
                'entity_type' => 'leads',
                'lookup_type' => 'lead_types',
                'validation' => null,
                'sort_order' => '5',
                'is_required' => '1',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'user_id',
                'name' => trans('installer::app.seeders.attributes.leads.sales-owner', [], $defaultLocale),
                'type' => 'select',
                'entity_type' => 'leads',
                'lookup_type' => 'users',
                'validation' => null,
                'sort_order' => '7',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'expected_close_date',
                'name' => trans('installer::app.seeders.attributes.leads.expected-close-date', [], $defaultLocale),
                'type' => 'date',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '8',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'lead_pipeline_id',
                'name' => trans('installer::app.seeders.attributes.leads.pipeline', [], $defaultLocale),
                'type' => 'lookup',
                'entity_type' => 'leads',
                'lookup_type' => 'lead_pipelines',
                'validation' => null,
                'sort_order' => '9',
                'is_required' => '1',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'lead_pipeline_stage_id',
                'name' => trans('installer::app.seeders.attributes.leads.stage', [], $defaultLocale),
                'type' => 'lookup',
                'entity_type' => 'leads',
                'lookup_type' => 'lead_pipeline_stages',
                'validation' => null,
                'sort_order' => '10',
                'is_required' => '1',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'budget',
                'name' => 'Budget',
                'type' => 'price',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '11',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'requirement',
                'name' => 'Requirement',
                'type' => 'textarea',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '12',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'timeline',
                'name' => 'Timeline',
                'type' => 'select',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '13',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'intent',
                'name' => 'Intent',
                'type' => 'select',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '14',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'decision_maker',
                'name' => 'Decision Maker',
                'type' => 'boolean',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '15',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ], [
                'code' => 'qualification_checklist',
                'name' => 'Qualification Checklist',
                'type' => 'multiselect',
                'entity_type' => 'leads',
                'lookup_type' => null,
                'validation' => null,
                'sort_order' => '16',
                'is_required' => '0',
                'is_unique' => '0',
                'quick_add' => '0',
                'is_user_defined' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
